name: Media Downloader

on:
  schedule:
    # Run every day at 6 AM EST (11 AM UTC)
    - cron: '0 11 * * *'
    
jobs:
  run-python-script:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10' # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # If you have dependencies, install them here
        # pip install -r requirements.txt
        pip install instagrapi
        pip install moviepy

    - name: Run Python script
      run: python download_GA.py

    - name: Count added files in videos directory
      id: count_added_files
      run: |
        ADDED_FILES=$(git status videos --porcelain | grep 'A  ' | wc -l)
        echo "added_files=$ADDED_FILES" >> $GITHUB_ENV
    
    - name: Set commit message
      id: set_commit_message
      run: |
        if [ ${{ env.added_files }} -gt 0 ]; then
          echo "commit_message=DOWNLOADER: ${{ env.added_files }} new videos" >> $GITHUB_ENV
        else
          echo "commit_message=DOWNLOADER: No new files added to videos directory" >> $GITHUB_ENV
        fi

    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: ${{ env.commit_message }}
