name: Media Downloader

on:
  workflow_dispatch:
    
jobs:
  run-python-script:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10' # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # If you have dependencies, install them here
        # pip install -r requirements.txt
        pip install instagrapi
        pip install moviepy

    - name: Run Python script
      run: python download_GA.py

    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Downloader: Adding videos"
