name: Update Cron Schedule

schedule:
  - cron: '0 10 * * *'

jobs:
  update-cron:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      actions: write

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Generate cron expressions
      id: generate_cron
      run: |
        python generate_cron.py > cron_output.txt
        cat cron_output.txt

    - name: Update workflow file with new cron expressions
      run: |
        # Remove existing cron expressions
        sed -i '/^    - cron: /d' .github/workflows/uploader.yml
        # Insert new cron expressions after the placeholder
        cron_output=$(cat cron_output.txt)
        sed -i "/# Initial placeholder for cron jobs/r cron_output.txt" .github/workflows/uploader.yml

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add .github/workflows/uploader.yml
        git commit -m "CRON EXPRESSION: randomizing minute"
        git push