name: Media Uploader

on:
  schedule:
    # Run every 45 minutes between 8 AM - 11 PM EST (1 PM - 4 AM UTC)
    - cron: '0,45 13-23 * * *'
    - cron: '0,45 0-3 * * *'
    
jobs:
  run-python-script:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10' # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # If you have dependencies, install them here
        # pip install -r requirements.txt
        pip install instagrapi
        pip install moviepy
        pip install tiktok_uploader

    - name: Run Python script
      run: python upload_GA.py

    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "UPLOADER: Removing video file"
