name: Media Uploader

on:
  schedule:
    # Initial placeholder for cron jobs, to be updated by the other workflow
    - cron: '48 12 * * *'
    - cron: '9 13 * * *'
    - cron: '5 14 * * *'
    - cron: '27 15 * * *'
    - cron: '38 16 * * *'
    - cron: '9 17 * * *'
    - cron: '23 18 * * *'
    - cron: '23 19 * * *'
    - cron: '14 20 * * *'
    - cron: '46 21 * * *'
    - cron: '27 22 * * *'
    - cron: '22 23 * * *'
    - cron: '36 0 * * *'
    - cron: '14 1 * * *'
    - cron: '13 2 * * *'
    - cron: '31 3 * * *'
    - cron: '41 4 * * *'
    - cron: '4 5 * * *'
    - cron: '10 6 * * *'

  workflow_dispatch:

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      workflows: write  # Add this line to grant workflows permission

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10' # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # If you have dependencies, install them here
        # pip install -r requirements.txt
        pip install instagrapi moviepy tiktok_uploader

    - name: Run Python script
      run: python tiktok/tiktok.py

    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "UPLOADER: Removing video file"