name: Media Uploader

on:
  schedule:
    # Initial placeholder for cron jobs, to be updated by the other workflow
    - cron: '19 12 * * *'
    - cron: '55 13 * * *'
    - cron: '47 14 * * *'
    - cron: '48 15 * * *'
    - cron: '11 16 * * *'
    - cron: '18 17 * * *'
    - cron: '13 18 * * *'
    - cron: '36 19 * * *'
    - cron: '55 20 * * *'
    - cron: '3 21 * * *'
    - cron: '56 22 * * *'
    - cron: '31 23 * * *'
    - cron: '25 0 * * *'
    - cron: '37 1 * * *'
    - cron: '54 2 * * *'
    - cron: '14 3 * * *'
    - cron: '29 4 * * *'
    - cron: '55 5 * * *'
    - cron: '16 6 * * *'

  workflow_dispatch:

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10' # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # If you have dependencies, install them here
        # pip install -r requirements.txt
        pip install instagrapi moviepy tiktok_uploader

    - name: Run Python script
      run: python upload_GA.py

    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "UPLOADER: Removing video file"