name: Media Uploader

on:
  schedule:
    # Initial placeholder for cron jobs, to be updated by the other workflow
    - cron: '5 12 * * *'
    - cron: '55 13 * * *'
    - cron: '21 14 * * *'
    - cron: '35 15 * * *'
    - cron: '57 16 * * *'
    - cron: '37 17 * * *'
    - cron: '17 18 * * *'
    - cron: '25 19 * * *'
    - cron: '29 20 * * *'
    - cron: '4 21 * * *'
    - cron: '49 22 * * *'
    - cron: '4 23 * * *'
    - cron: '23 0 * * *'
    - cron: '25 1 * * *'
    - cron: '56 2 * * *'
    - cron: '56 3 * * *'
    - cron: '48 4 * * *'
    - cron: '46 5 * * *'
    - cron: '6 6 * * *'

  workflow_dispatch:

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10' # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # If you have dependencies, install them here
        # pip install -r requirements.txt
        pip install instagrapi moviepy tiktok_uploader

    - name: Run Python script
      run: python upload_GA.py

    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "UPLOADER: Removing video file"