name: Media Uploader

on:
  workflow_dispatch:
    # Initial placeholder for cron jobs, to be updated by the other workflow
jobs:
  run-python-script:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      workflows: write  # Add this line to grant workflows permission

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10' # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # If you have dependencies, install them here
        # pip install -r requirements.txt
        pip install instagrapi moviepy tiktok_uploader

    - name: Run Python script
      run: python tiktok/tiktok.py

    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "UPLOADER: Removing video file"
    - cron: '29 12 * * *'
    - cron: '16 13 * * *'
    - cron: '24 14 * * *'
    - cron: '53 15 * * *'
    - cron: '59 16 * * *'
    - cron: '56 17 * * *'
    - cron: '19 18 * * *'
    - cron: '57 19 * * *'
    - cron: '47 20 * * *'
    - cron: '54 21 * * *'
    - cron: '6 22 * * *'
    - cron: '43 23 * * *'
    - cron: '53 0 * * *'
    - cron: '26 1 * * *'
    - cron: '19 2 * * *'
    - cron: '41 3 * * *'
    - cron: '46 4 * * *'
    - cron: '6 5 * * *'
    - cron: '24 6 * * *'
