name: Media Uploader

on:
  schedule:
    # Initial placeholder for cron jobs, to be updated by the other workflow
    - cron: '30 12 * * *'
    - cron: '38 13 * * *'
    - cron: '33 14 * * *'
    - cron: '14 15 * * *'
    - cron: '27 16 * * *'
    - cron: '9 17 * * *'
    - cron: '12 18 * * *'
    - cron: '5 19 * * *'
    - cron: '51 20 * * *'
    - cron: '14 21 * * *'
    - cron: '20 22 * * *'
    - cron: '58 23 * * *'
    - cron: '46 0 * * *'
    - cron: '31 1 * * *'
    - cron: '33 2 * * *'
    - cron: '44 3 * * *'
    - cron: '25 4 * * *'
    - cron: '25 5 * * *'
    - cron: '7 6 * * *'

  workflow_dispatch:

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10' # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # If you have dependencies, install them here
        # pip install -r requirements.txt
        pip install instagrapi moviepy tiktok_uploader

    - name: Run Python script
      run: python upload_GA.py

    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "UPLOADER: Removing video file"