name: Media Uploader

on:
  scheldue:
    # Initial placeholder for cron jobs, to be updated by the other workflow
    - cron: '52 12 * * *'
    - cron: '52 13 * * *'
    - cron: '18 14 * * *'
    - cron: '15 15 * * *'
    - cron: '36 16 * * *'
    - cron: '30 17 * * *'
    - cron: '11 18 * * *'
    - cron: '16 19 * * *'
    - cron: '11 20 * * *'
    - cron: '10 21 * * *'
    - cron: '32 22 * * *'
    - cron: '36 23 * * *'
    - cron: '7 0 * * *'
    - cron: '37 1 * * *'
    - cron: '53 2 * * *'
    - cron: '9 3 * * *'
    - cron: '49 4 * * *'
    - cron: '54 5 * * *'
    - cron: '38 6 * * *'
    
jobs:
  run-python-script:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      workflows: write  # Add this line to grant workflows permission

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10' # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # If you have dependencies, install them here
        # pip install -r requirements.txt
        pip install instagrapi moviepy tiktok_uploader

    - name: Run Python script
      run: python tiktok/tiktok.py

    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "UPLOADER: Removing video file"