name: Media Uploader

on:
  schedule:
    # Initial placeholder for cron jobs, to be updated by the other workflow
    - cron: '8 12 * * *'
    - cron: '46 13 * * *'
    - cron: '55 14 * * *'
    - cron: '31 15 * * *'
    - cron: '43 16 * * *'
    - cron: '39 17 * * *'
    - cron: '54 18 * * *'
    - cron: '38 19 * * *'
    - cron: '50 20 * * *'
    - cron: '54 21 * * *'
    - cron: '44 22 * * *'
    - cron: '46 23 * * *'
    - cron: '51 0 * * *'
    - cron: '19 1 * * *'
    - cron: '4 2 * * *'
    - cron: '11 3 * * *'
    - cron: '41 4 * * *'
    - cron: '32 5 * * *'
    - cron: '28 6 * * *'

  workflow_dispatch:

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10' # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # If you have dependencies, install them here
        # pip install -r requirements.txt
        pip install instagrapi moviepy tiktok_uploader

    - name: Run Python script
      run: python upload_GA.py

    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "UPLOADER: Removing video file"