name: Media Uploader

on:
  schedule:
    # Initial placeholder for cron jobs, to be updated by the other workflow
    - cron: '30 12 * * *'
    - cron: '20 13 * * *'
    - cron: '8 14 * * *'
    - cron: '53 15 * * *'
    - cron: '19 16 * * *'
    - cron: '19 17 * * *'
    - cron: '36 18 * * *'
    - cron: '9 19 * * *'
    - cron: '15 20 * * *'
    - cron: '1 21 * * *'
    - cron: '20 22 * * *'
    - cron: '47 23 * * *'
    - cron: '58 0 * * *'
    - cron: '48 1 * * *'
    - cron: '6 2 * * *'
    - cron: '53 3 * * *'
    - cron: '39 4 * * *'
    - cron: '43 5 * * *'
    - cron: '3 6 * * *'

  workflow_dispatch:

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10' # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # If you have dependencies, install them here
        # pip install -r requirements.txt
        pip install instagrapi moviepy tiktok_uploader

    - name: Run Python script
      run: python upload_GA.py

    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "UPLOADER: Removing video file"