name: Media Uploader

on:
  schedule:
    - cron: '45 12 * * *'
    - cron: '40 13 * * *'
    - cron: '9 14 * * *'
    - cron: '47 15 * * *'
    - cron: '1 16 * * *'
    - cron: '49 17 * * *'
    - cron: '36 18 * * *'
    - cron: '38 19 * * *'
    - cron: '4 20 * * *'
    - cron: '6 21 * * *'
    - cron: '23 22 * * *'
    - cron: '30 23 * * *'
    - cron: '22 0 * * *'
    - cron: '4 1 * * *'
    - cron: '0 2 * * *'
    - cron: '56 3 * * *'
    - cron: '34 4 * * *'
    - cron: '23 5 * * *'
    - cron: '11 6 * * *'

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      workflows: write  # Add this line to grant workflows permission

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10' # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # If you have dependencies, install them here
        # pip install -r requirements.txt
        pip install instagrapi moviepy tiktok_uploader

    - name: Run Python script
      run: python tiktok/tiktok.py

    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "UPLOADER: Removing video file"