name: Media Uploader

on:
  schedule:
    # Initial placeholder for cron jobs, to be updated by the other workflow
    - cron: '27 12 * * *'
    - cron: '38 13 * * *'
    - cron: '52 14 * * *'
    - cron: '21 15 * * *'
    - cron: '16 16 * * *'
    - cron: '24 17 * * *'
    - cron: '30 18 * * *'
    - cron: '41 19 * * *'
    - cron: '48 20 * * *'
    - cron: '1 21 * * *'
    - cron: '28 22 * * *'
    - cron: '7 23 * * *'
    - cron: '35 0 * * *'
    - cron: '49 1 * * *'
    - cron: '36 2 * * *'
    - cron: '41 3 * * *'
    - cron: '24 4 * * *'
    - cron: '28 5 * * *'
    - cron: '39 6 * * *'

  workflow_dispatch:

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10' # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # If you have dependencies, install them here
        # pip install -r requirements.txt
        pip install instagrapi moviepy tiktok_uploader

    - name: Run Python script
      run: python upload_GA.py

    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "UPLOADER: Removing video file"