name: Media Uploader

on:
  schedule:
    # Initial placeholder for cron jobs, to be updated by the other workflow
    - cron: '53 12 * * *'
    - cron: '30 13 * * *'
    - cron: '39 14 * * *'
    - cron: '45 15 * * *'
    - cron: '19 16 * * *'
    - cron: '30 17 * * *'
    - cron: '56 18 * * *'
    - cron: '41 19 * * *'
    - cron: '41 20 * * *'
    - cron: '50 21 * * *'
    - cron: '41 22 * * *'
    - cron: '25 23 * * *'
    - cron: '48 0 * * *'
    - cron: '57 1 * * *'
    - cron: '10 2 * * *'
    - cron: '23 3 * * *'
    - cron: '18 4 * * *'
    - cron: '59 5 * * *'
    - cron: '15 6 * * *'
  workflow_dispatch:

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10' # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # If you have dependencies, install them here
        # pip install -r requirements.txt
        pip install instagrapi moviepy tiktok_uploader

    - name: Run Python script
      run: python tiktok/tiktok.py

    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "UPLOADER: Removing video file"